version: '2'
services:
  debug:
    image: phpstorm/php-71-apache-xdebug
    ports:
      - "8081:80"
    volumes:
      - ./banco.bradesco/html/classic/index.shtm
    environment:
      #For Windows and macOS, replace the line below with `host.docker.internal`, which will automatically resolve to the internal address of the host Docker is running on.
      #For Linux, replace the line below with your hostname, which you can obtain by executing `hostname` in Terminal.
      XDEBUG_CONFIG: https://banco.bradesco/html/classic/index.shtm

      #For macOS, if you use a local Homebrew php-fpm installation, port `9000` (which is the default debugging port) may become occupied. PhpStorm will remain silent on starting listening for incoming connections. If this is the case, in the Settings | Languages & Frameworks | PHP | Debug, set the Debug port to 9001, and use the following configuration line instead.

      #XDEBUG_CONFIG: remote_host=host.docker.internal, remote_port=9001

  sftp:
    image: phpstorm/sftp-server
    ports:
      - "2022:22"
    volumes:
      #   Uncomment for Windows
      # - C:/temp:/home/jetbrains/upload
        #   Uncomment for macOS/Linux
      # - /tmp:/home/jetbrains/upload
    command: console
  mysql:
    image: phpstorm/mysql
    ports:
      - "33056:3306"
    volumes:
      - ./data:/var/lib/mysql